### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [tacahilo/packer-FreeBSD-10.0#1]
First of all, thanks for creating and sharing a nice packer template for FreeBSD 10.0!
Could you add LICENSE file?

This page may help for choosing a license.
[Choosing an OSS license doesn’t need to be scary - ChooseALicense.com](http://choosealicense.com/)

Thanks!

**Comment by hfm** [comment]
Add MIT License at 4652e19 . Thanks :)
